axis_linear: 1  # Left thumb stick vertical
scale_linear: 20
scale_linear_turbo: 20

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 20

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button
